### ISSUE TITLE
DRAFT 03 Cohort Call Digest [ 2021-noaa-nmfs ] 

### ISSUE THREAD

**Issue by cclatterbuck** [Openscapes/2021-noaa-nmfs#34]
Approved/done (internal):

- [x] Corey
- [ ] Julie
- [ ] Eli

Review below and add new text in between the `[ ]`'s. Specifically, double-check
- [ ] co-working times
- [ ] under Goals: a good reference page for Chanté (the ones I googled weren't very recent)
- [ ] adding any links from Emily
- [ ] adding any links from Kim (2021-fdd)
- [ ] maybe add [RGovies](https://rgovys.github.io/) resource somewhere? 
- [ ] double-check all links

---
Hi All,

Thanks for a great third session last Friday. Thank you to Chanté Davis for guest teaching about Coding Strategies for Future Us and providing insights to planning workflows with R and communicating the needs for those plans in IDPs! Below is a light digest of Call 3, including a reminder for your Seaside Chat [ and additional Co-Working times ] before our Call 4 on Friday, October 29th. Looking forward to seeing you then!

Have a good week,

Julie & Eli & Corey

## Digest: Cohort Call 4 [ 2021-noaa-nmfs ]

[CohortCalls folder](https://drive.google.com/drive/u/1/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn) - contains video recordings and completed agendas
[openscapes.github.io/2021-noaa-nfms](https://openscapes.github.io/2021-noaa-nmfs) - Cohort webpage

**Goals:** We’ll discuss open communities and NOAA coding communities with special guest [Chanté Davis]() (NOAA Fisheries' West Coast Region) as strategies for future us.

**Task for next time: Explore community resources, prepare to present your Pathway**

1. Have a Seaside Chat with your broader research group
    * Explore more Community Tools
    
2. Prepare to present your Pathway on Call 4 (Oct 29)
    * Each group has 5 minutes to share their pathway: (3 min present + 2 min Qs)
    * Share your Pathway Doc in our [PathwayShare folder](https://drive.google.com/drive/folders/1JgsXSY6EASG5wuczF-INs12O4QMC8xZn?usp=sharing) before Call 4
    
3. Co-working: (optional). This is a time to come work on your own things, but also be able to talk things through and screenshare to get help from others. Schedule upcoming - check your emails for Calendar Invite with Zoom links.

4. Have a 1-1 appointment with Eli (optional). Sign up via [Google appointments](https://calendar.google.com/calendar/u/0/selfsched?sstoken=UUdnTHRDSXJxX2FufGRlZmF1bHR8ZjY4ZjJhZTk0ODI5ZDUxODlkN2Y4NmI3Njc3MGI5OTY)

**Slide Decks:**

These are also available publicly from [openscapes.org/series](https://openscapes.github.io/series)

* [Open Communities](https://docs.google.com/presentation/d/17HSNmBYvPw-7Prioys7WIhL9QGVb3s3bJCLaAJVaChc/edit?usp=sharing)
* [Coding Strategies for Future Us: Expanding OuR Communities](https://docs.google.com/presentation/d/1a620vM5OkOgcUi0I-mQPV5ZTQglRfwSnAb6O41g8tv0/edit?usp=sharing)
* [Discovering Community Tools](https://docs.google.com/presentation/d/1czvMz7a84jkaYDwHlG1cuKyf9B0mciQJVOFcc7hZtpU/edit#slide=id.p) -- we did not review this during the call, but these might be a helpful place to start for exploring more community tools, potentially during a seaside chat.

**Slack**

We sent invitations to the Openscapes Slack Organization so that you can connect further with our Cohort (private channel) and with the Openscapes Community ([quick start guide](https://zenodo.org/record/3763730#.YVdZ_ZrMLIV)).

**A few lines from shared notes in the Agenda doc:**
* Teams had lots of questions about how to onboard and work with people who don't currently use these workflows. The AFSC group had some suggestions in this the 03 Call Agenda notes, and Eli suggested starting with one project that needs to move to version control & testing with that. 
* we should have a show and tell of automated reports - they're all a little different and I want to learn from other peoples' experiences! +1, Openscapes is open to supporting this effort as well.
* Don't R alone! Build a community means R has to be in your work plan.
* When discussing the need for time to create R code, consider different messaging for different audiences. While making a table faster isn’t so exciting to higher-ups, number of reports faster maybe more so. 
* Think of the Netflix show [Nailed It!](https://en.wikipedia.org/wiki/Nailed_It!) and normalize failure -- think of this process and something to do and learn from
* Approach & map project management and workflows like a recipe: What is the end product? What are the steps to create the end product? Which of these steps can be automated?

**Comment by jules32** [comment]
Hi @Openscapes/2021-noaa-nmfs-team ! 

This is the finalized Digest from Call 03. Hope you're having a good week! Check out the additional events Friday and Tuesday before our last Cohort Call on Oct 29. 
https://github.com/Openscapes/2021-noaa-nmfs/issues/34

Hope you're having a good week!
